package momime.client.calculations;

import java.awt.image.BufferedImage;
import java.io.IOException;

import momime.common.database.RecordNotFoundException;
import momime.common.messages.v0_9_5.MapAreaOfCombatTiles;

import com.ndg.map.coordinates.MapCoordinates3DEx;

/**
 * Deals with deriving combat tiles and generating the combat scenery bitmap.
 */
public interface CombatMapBitmapGenerator
{
	/**
	 * Creates the smoothedTiles array as the correct size
	 */
	public void afterJoinedSession ();
	
	/**
	 * Converts the tile types sent by the server into actual tile numbers, smoothing the edges of various terrain types in the process
	 * 
	 * @param combatLocation Overland map coordinates where combat it taking place (we need to know e.g. what tile type it is there and what plane it is on)
	 * @param combatTerrain Scenery tiles generated by the server for this combat map
	 * @throws RecordNotFoundException If required entries in the graphics XML cannot be found
	 */
	public void smoothMapTerrain (final MapCoordinates3DEx combatLocation, final MapAreaOfCombatTiles combatTerrain) throws RecordNotFoundException;

	/**
	 * Generates big bitmaps of the entire overland map in each frame of animation.
	 * Delphi client did this rather differently, by building Direct3D vertex buffers to display all the map tiles; equivalent method there was RegenerateCompleteSceneryView.
	 * 
	 * Generated bitmaps will all be 20x countX by 18x countY pixels in size.
	 * 
	 * @return Combat map bitmap
	 * @throws IOException If there is a problem loading any of the images
	 */
	public BufferedImage generateCombatMapBitmap () throws IOException;
}